# Generated by Django 5.2.4 on 2025-08-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation'),
        ),
        migrations.AddField(
            model_name='policyanalysis',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='policyanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policycomparison',
            name='policy1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_first', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='policycomparison',
            name='policy2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_second', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='policycomparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_comparisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='policycomparison',
            unique_together={('policy1', 'policy2', 'user')},
        ),
    ]
