# Generated by Django 5.2.4 on 2025-08-19 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
        ('policies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='policyanalysis',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='policyanalysis',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='policycomparison',
            unique_together={('user', 'policy1', 'policy2')},
        ),
        migrations.AddField(
            model_name='policycomparison',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='policycomparison',
            name='comparison_criteria',
            field=models.JSONField(default=dict, verbose_name='Comparison Criteria'),
        ),
        migrations.AlterField(
            model_name='policycomparison',
            name='comparison_score',
            field=models.IntegerField(default=0, verbose_name='Comparison Score'),
        ),
        migrations.AlterField(
            model_name='policycomparison',
            name='detailed_analysis',
            field=models.JSONField(default=dict, verbose_name='Detailed Analysis'),
        ),
        migrations.AlterField(
            model_name='policycomparison',
            name='policy1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_policy1', to='policies.policy'),
        ),
        migrations.AlterField(
            model_name='policycomparison',
            name='policy2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_policy2', to='policies.policy'),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PolicyAnalysis',
        ),
        migrations.RemoveField(
            model_name='policycomparison',
            name='recommendations',
        ),
    ]
