# Generated by Django 5.2.4 on 2025-08-16 13:45

import django.core.validators
import policies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Policy Name')),
                ('provider', models.CharField(max_length=255, verbose_name='Insurance Provider')),
                ('policy_type', models.CharField(choices=[('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('life', 'Life Insurance'), ('business', 'Business Insurance'), ('other', 'Other')], max_length=20, verbose_name='Policy Type')),
                ('policy_number', models.CharField(blank=True, max_length=100, verbose_name='Policy Number')),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Coverage Amount')),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Premium Amount')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Policy Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Policy End Date')),
                ('document', models.FileField(upload_to=policies.models.policy_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])], verbose_name='Policy Document')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(max_length=10, verbose_name='File Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(verbose_name='Extracted Text')),
                ('text_length', models.PositiveIntegerField(verbose_name='Text Length')),
                ('extraction_date', models.DateTimeField(auto_now_add=True, verbose_name='Extraction Date')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Extraction Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Policy Extraction',
                'verbose_name_plural': 'Policy Extractions',
                'db_table': 'policy_extractions',
            },
        ),
    ]
