# Generated by Django 5.2.4 on 2025-08-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyextraction',
            name='policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='policies.policy'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['user', 'policy_type'], name='policies_user_id_3e0c23_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['provider'], name='policies_provide_af3d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['created_at'], name='policies_created_893bbd_idx'),
        ),
    ]
